# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
command_timeout = 800

format = """\
$os\
$directory\
$git_branch\
$git_status\
$git_metrics\
[](fg:#b2b2b2)\
$fill\
$status\
$cmd_duration\
$kubernetes\
$aws\
$docker_context\
$golang\
$terraform\
$time\
[](fg:#b2b2b2)
$line_break\
$character
"""

continuation_prompt = '[▶▶ ](green)'

[os]
disabled = false
format = "[╭─](fg:#434344)[](fg:#b2b2b2)[ $symbol ](fg:black bg:#b2b2b2)[](fg:#b2b2b2 bg:#0097a7)"
symbols.Macos = ""

[character]
format ="[╰─](fg:#434344)$symbol "
success_symbol = "[❯](bold red)[❯](bold yellow)[❯](bold green)"
error_symbol = "[❯❯❯](bold red)"

[directory]
format = "[  $path $read_only ](bg:#0097a7)"
truncate_to_repo = true
truncation_length = 2
truncation_symbol = ".../"
fish_style_pwd_dir_length = 3
read_only = ""

[git_branch]
format = '[ $symbol $branch(:$remote_branch) ]($style)'
symbol = " "
style = "fg:black bg:yellow"

[git_status]
format = '[(\[$all_status($ahead_behind)\])]($style)'
ahead = '⇡${count}'
diverged = '⇕⇡$ahead_count⇣$behind_count'
behind = '⇣${count}'
style = "fg:#1C3A5E bg:yellow"

[git_metrics]
disabled = false
format = "([+$added]($added_style))[]($added_style)"
added_style = "fg:#1C3A5E bg:yellow"
deleted_style = "fg:red bg:yellow"

[status]
disabled = false
style = 'bg:black'
symbol = '[✘](fg:red)'
success_symbol = '[✔](fg:green bg:black)'
format = '[](fg:black)[$symbol $common_meaning$signal_name$maybe_int ]($style)'
map_symbol = true

[cmd_duration]
disabled = false
min_time = 2000
format = '[$duration ]($style)'
style = 'fg:yellow bg:black bold'

[time]
disabled = false
time_format = '%T'
format = '[ $time  ](fg:black bg:#b2b2b2)'
# style = "fg:black bg:#b2b2b"

[kubernetes]
disabled = false
symbol = '󱃾'
format = '[ $symbol $context \($namespace\) ](bg:#0097a7)'
style = 'cyan bold'

[kubernetes.context_aliases]
# user@cluster-name.ap-southeast-1.eksctl.io
'(?P<user>.*)@(?P<name>.*)\.(?P<region>.*).eksctl.io' = "$name"
# arn:aws:eks:ap-southeast-1:11111111:cluster/eks
'arn:aws:eks:(?P<region>.*):(?P<account>.*):cluster/(?P<name>.*)' = '$name'

[aws]
format = '[ $symbol ($profile )(\[$duration\] )]($style)'
style = 'bg:#f19e38'
symbol = '󰸏'

[docker_context]
format = '[ $symbol $context ]($style)'
symbol = ''
style = "fg:black bg:#3f8fdc"

[golang]
format = '[ $symbol ($version )($mod_version )]($style)'
symbol = ""
style = "fg:black bg:#7AD0F3"

[terraform]
format = '[ $symbol $version ]($style)'
symbol = ""
style = "fg:black bg:#5842D9"

[fill]
symbol = '·'
style = 'bold #434344'

[line_break]
disabled = true

[custom.foo]
command = "echo ->$@"
# command = "echo |"
when = "true"
format = "[$symbol($output)](green)"
use_stdin = true